name: 'Setup Python + Poetry environment'
description: 'Setup Python + Poetry environment'

inputs:
  python-version:
    required: false
    description: 'Python version'
    default: '3.10'
  cache:
    required: false
    description: 'Cache option'
    default: 'poetry'
outputs: {}
runs:
  using: 'composite'
  steps:
    - id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.python-version}}
        cache: ${{inputs.cache}}
    - id: install-poetry
      uses: snok/install-poetry@v1.2
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - id: create-virtual-environment
      name: Create virtual environment
      run: poetry install
      shell: bash
